### ISSUE TITLE
Timeline for releasing latest pull request (develop branch)

### ISSUE THREAD

**Issue by bnystrom** [technocreatives/node-red-contrib-can#3]
Hi,
I was wondering if you had a roadmap/timeline for merging/releasing the current develop branch. If it will be some time off then I think we'll release our own fork with those changes so our clients can install it in node-red via npmjs.

Regards,
Bryan

**Comment by magnussp** [comment]
Hello Bryan!

Thanks for your contribution. I can check and make a release to npmjs next
week as I'm AFK untill then.

I hope this works for you.

Best regards
Magnus

**Comment by bnystrom** [comment]
Magnus,

Awesome. Thanks
